### PR TITLE
Make topic slugs unique across messageboards

### LINKED ISSUE #573: Redirect to canonical topic url if messageboard slug is wrong
A topics may be moved to another messageboard. Need to redirect instead of 404, so that the old URLs still work.

### PR DESCRIPTION
**Pull request by glebm**
This allows us to correctly redirect to the new topic URL when the topic's messageboard has changed.

Resolves #573

Needs code review!

### CODE REVIEW

File: app/models/thredded/topic.rb [hunk 1]
```diff
@@ -22,8 +22,7 @@ class Topic < ActiveRecord::Base # rubocop:disable Metrics/ClassLength
 
     extend FriendlyId
     friendly_id :slug_candidates,
-                use:            [:history, :reserved, :scoped],
-                scope:          :messageboard,
+                use: %i(history reserved),
                 # Avoid route conflicts
```
Comment (timdiggins) [inline app/models/thredded/topic.rb]: do the words "Avoid route conflicts" fill anyone else with horror?

**Comment by timdiggins** [comment]
Having a look at the PR, but this allows me to ask a question about FriendlyId. 

How committed are we to the current "Friendly" urls. 

I so much prefer trello's style of friendly urls (id plus descriptive but irrelevant text) which are automatically unique and don't really require much special treatment. Anyone who looks at URLs a lot will understand the trello ones. And many people who don't understand the trello ones won't bother to look at the URLs at all.

I just feel FriendlyId's (unique, historical, id-hiding) url is causing a lot of work and some danger (see https://github.com/thredded/thredded/pull/576/commits/a196e550e59b61866f8445c3338e3f4f6fa4bfc5#r113638127 for example). Is it really worth this effort. (kind of obvious which way I fall on this, but what do you think @glebm, @jayroh

**Comment by glebm** [comment]
I think it's worth the effort due because these URLs are slightly more SEO-friendly. They're hard to get right, but I think with this PR we will have nailed it.

> And many people who don't understand the trello ones won't bother to look at the URLs at all.

Not in the browser URL bar, but the URLs are also displayed in Google search results. Compare:

a) The full URL is displayed:
plforums-search-result
b) Part of the URL is hidden because of the numeric ID taking up space:
discourse-search-result

**Comment by timdiggins** [comment]
good answer @glebm -- ok, I can see why this makes sense to public forum users.
