### PR TITLE
Fix post page path and extract UrlHelpers

### LINKED ISSUE #201: Redirect after making a post should be to the post's page

### PR DESCRIPTION
**Pull request by glebm**
Resolves #201

### CODE REVIEW

**Comment by glebm** [comment]
Fixed rubocop warning

File: app/mailer_previews/thredded/base_mailer_preview.rb [hunk 1]
```diff
@@ -3,9 +3,7 @@ module Thredded
   # @abstract
   class BaseMailerPreview
     def self.preview_classes
-      Dir[File.join(File.dirname(__FILE__), '*_preview.rb')].map do |p|
-        "Thredded::#{File.basename(p, '.rb').camelize}"
-      end
+      RailsEmailPreview.find_preview_classes File.expand_path('..', File.dirname(__FILE__))
```
Comment (jayroh) [inline app/mailer_previews/thredded/base_mailer_preview.rb]: Saw this just landed in REP. Great stuff! :)
